# Generated by Django 5.1.1 on 2024-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_room_latitude_room_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronJobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cron_job", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_success", models.BooleanField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cron_job", "start_time"],
                        name="base_cronjo_cron_jo_4539eb_idx",
                    )
                ],
            },
        ),
    ]
