# Generated by Django 5.1.1 on 2024-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_notifications_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="NotificationPreference",
        ),
    ]
