# Generated by Django 5.1.1 on 2024-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tele',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
