# Generated by Django 5.1.1 on 2024-11-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_tele'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tele',
            new_name='telegram_id',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
