# Generated by Django 5.1.1 on 2024-10-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="location",
            field=models.CharField(default="Unknown location", max_length=255),
        ),
        migrations.AddField(
            model_name="room",
            name="pax_required",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
