# Generated by Django 5.1.1 on 2024-10-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_topic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="latitude",
            field=models.FloatField(default=1.3521),
        ),
        migrations.AddField(
            model_name="room",
            name="longitude",
            field=models.FloatField(default=103.8198),
        ),
    ]
