# Generated by Django 5.1.1 on 2024-10-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_room_latitude_room_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="court_image",
            field=models.ImageField(blank=True, null=True, upload_to="courts/"),
        ),
    ]
