# Generated by Django 5.1.1 on 2024-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_room_date_room_end_time_room_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(default="Basketball", max_length=200),
        ),
    ]
