# Generated by Django 5.1.1 on 2024-10-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_remove_room_court_image_remove_room_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
