# Generated by Django 5.1.1 on 2024-11-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_user_email_notifications_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
